### ISSUE TITLE
Training Setup Error

### ISSUE THREAD

**Issue by logbarron** [weijun88/SANet#2]
Hello! I do apologize if this is something easily fixed that I missed, but it seems that the current training code throws an error related to the name2 color2. Any ideas where I might be going wrong?

```
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    t.train()
  File "train.py", line 98, in train
    for image, mask in self.loader:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 434, in reraise
    raise exception
ZeroDivisionError: Caught ZeroDivisionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "train.py", line 46, in __getitem__
    name2  = self.color1[idx%len(self.color1)] if np.random.rand()<0.7 else self.color2[idx%len(self.color2)]
ZeroDivisionError: integer division or modulo by zero
```

**Comment by weijun-arc** [comment]
Please print the variables of self.color1, self.color2 and self.samples. I guess you have changed the file path or file name that all these variables are empty.

**Comment by logbarron** [comment]
ah! my apologies, appears it was a super simple error on my part. did not have all the testing folders with imagery. all good! thank you for the reply.
